In [1]:
import pandas as pd

In [3]:
a = pd.read_csv("all_sp500_stocks_1years_daily")

In [4]:
a

,ds,A,AAL,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,...,WTW,WY,WYNN,XEL,XOM,XYL,YUM,ZBH,ZBRA,ZTS
0,2023-07-03,118.686035,18.100000,191.443298,129.743484,132.350006,105.089409,73.989998,306.257202,485.209991,...,230.223083,32.595253,105.506874,60.619061,103.804726,110.493378,134.647827,141.337601,296.269989,168.586594
1,2023-07-05,118.865082,18.320000,190.319260,132.251678,131.690002,105.236420,73.620003,305.203430,487.260010,...,228.763718,32.303707,100.687706,61.398693,103.273438,108.902618,134.049484,141.188843,292.850006,167.715103
2,2023-07-06,117.800766,17.879999,190.796738,131.896103,128.160004,105.069801,73.870003,303.302673,481.290009,...,228.024200,31.740042,98.490883,61.369820,99.419159,108.230743,131.342194,140.038376,291.140015,166.843582
3,2023-07-07,116.378357,18.350000,189.672684,130.214386,130.320007,104.236694,74.790001,301.126160,485.269989,...,227.619919,32.507793,100.262199,60.570934,99.650993,108.260384,130.900803,139.701187,295.220001,165.526413
4,2023-07-10,117.731140,18.570000,187.613632,129.243790,131.710007,104.893372,74.709999,303.775391,496.350006,...,229.700485,32.945118,105.971954,60.301434,101.128944,110.404449,132.234802,141.337601,306.160004,168.576691
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,2024-06-25,134.690002,11.130000,209.070007,170.750000,150.910004,105.489998,102.150002,307.170013,526.880005,...,262.193207,28.280001,88.300003,53.740002,114.370003,136.929993,132.330002,107.980003,306.040009,167.979996
247,2024-06-26,133.089996,11.120000,213.250000,171.149994,150.000000,104.879997,99.769997,304.619995,528.659973,...,262.771271,27.959999,88.129997,53.790001,114.410004,136.210007,131.960007,108.110001,307.119995,170.899994
248,2024-06-27,130.800003,11.280000,214.100006,168.990005,151.610001,104.650002,101.019997,303.190002,546.760010,...,263.149994,28.219999,89.139999,53.849998,114.900002,136.389999,132.610001,108.379997,306.989990,176.460007
249,2024-06-28,129.630005,11.330000,210.619995,171.520004,151.630005,103.910004,100.889999,303.410004,555.539978,...,262.140015,28.389999,89.500000,53.410000,115.120003,135.630005,132.460007,108.529999,308.929993,173.360001
250,2024-07-01,130.085007,11.245000,213.549896,172.050003,150.390106,104.610001,101.019997,301.339996,555.169983,...,262.679993,28.030001,88.400002,53.480000,116.014999,133.199997,130.740005,107.919998,306.260010,174.520004